# Generated by Django 2.2.4 on 2019-09-26 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_usercluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('height', models.CharField(blank=True, max_length=20)),
                ('spouse', models.TextField(blank=True)),
                ('biography', models.TextField(blank=True)),
                ('birth_date', models.DateTimeField(blank=True)),
                ('birch_notes', models.CharField(blank=True, max_length=100)),
                ('headshot', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Writers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Movie')),
                ('personid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Person')),
            ],
        ),
        migrations.CreateModel(
            name='SubScribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateTimeField()),
                ('subscribedate', models.DateTimeField()),
                ('autoscribe', models.BooleanField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Movie')),
                ('personid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Casts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Movie')),
                ('personid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Person')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(related_name='cast', through='api.Casts', to='api.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(related_name='director', through='api.Directors', to='api.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='writer',
            field=models.ManyToManyField(related_name='writer', through='api.Writers', to='api.Person'),
        ),
    ]
