# Generated by Django 2.2.4 on 2019-09-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190926_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdbrates',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='movie',
            name='plot',
            field=models.TextField(blank=True, default=''),
        ),
    ]
