# Generated by Django 2.2.4 on 2019-09-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190926_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='cluster',
            field=models.CharField(default='', max_length=20),
        ),
    ]
